let Give_me_a_code_for_a_car_stoppage_system_made_with_arduino_it_has_an_LCD_screen_I2C_A_DC_geared_mottor_and_an_MQ3_as_sensor_of_alcohol_it_has_to_stop_the_DC_geared_mottor_slowly_when_the_sensor_detects_more_than_05_mg_in_the_MQ3_It_all_needs_to_be_shown_in_the_LCD_screen = 0
basic.forever(function () {
    Give_me_a_code_for_a_car_stoppage_system_made_with_arduino_it_has_an_LCD_screen_I2C_A_DC_geared_mottor_and_an_MQ3_as_sensor_of_alcohol_it_has_to_stop_the_DC_geared_mottor_slowly_when_the_sensor_detects_more_than_05_mg_in_the_MQ3_It_all_needs_to_be_shown_in_the_LCD_screen = 0
})
basic.forever(function () {
    basic.showNumber(0)
})
